

let magicTableA = [
    "Potion of Healing",
    "Spell Scroll(cantrip)",
    "Potion of Climbing",
    "Spell Scroll(1st Level)",
    "Spell Scroll(2nd Level)",
    "Potion of Greater Healing",
    "Bag of Holding",
    "Driftglobe"
    ];
let magicTableB = [
    "Potion of Greater Healing",
    "Potion of fire breath",
    "Potion of resistance",
    "Ammunition +1",
    "Potion of animal friendship",
    "Potion of hill giant strength",
    "Potion of growth",
    "Potion of water breathing",
    "Spell scroll(2nd level)",
    "Spell scroll(3rd level)",
    "Bag of holding",
    "Keoghtom's ointment",
    "Oil of slipperiness",
    "Dust of disapperance",
    "Dust of dryness",
    "Dust of sneezing and choking",
    "Elemental gem",
    "Philter of love",
    "Alchemy jug",
    "Cap of water breathing",
    "Cloak of hte manta ray",
    "Driftglobe",
    "Goggles of night",
    "Helm of comprehending languages",
    "Immovable rod",
    "Lantern of revealing",
    "Mariner's armor",
    "Mithral armor",
    "Potion of poison",
    "Ring of Swimming",
    "Robe of useful items",
    "Rope of climbing",
    "Saddle of the cavalier",
    "Wand of magic detection",
    "Wand of secrets"
    ];
let magicTableC = [
    "Potion of superior Healing",
    "Spell scroll(4th level)",
    "Ammunition +2",
    "Potion of clairvoyance",
    "Potion of diminution",
    "Potion of gaseous form",
    "Potion of frost giant strength",
    "Potion of stone giant strength",
    "Potion of heroism",
    "Potion of invulnerability",
    "Potion of mind reading",
    "Spell scroll(5th level)",
    "Elixir of health",
    "Oil of etherealness",
    "Potion of fire giant strength",
    "Quaal's feather token",
    "Scroll of protection",
    "Bag of Beans",
    "Bead of force",
    "Chime of opening",
    "Decanter of endless water",
    "Eyes of minute seeing",
    "Folding boat",
    "Heward's handy haversack",
    "Horseshoes of speed",
    "Necklace of fireballs",
    "Periapt of health",
    "Sending stones"
    ];
let magicTableD = [
    "Potion of supreme healing",
    "Potion of invisibility",
    "Potion of speed",
    "Spell scroll(6th level)",
    "Spell scroll(7th level)",
    "Ammunition +3",
    "Oil of sharpness",
    "Potion of flying",
    "Potion of cloud giant strength",
    "Potion of longevity",
    "Potion of vitality",
    "Spell scroll(8th level)",
    "Horseshoes of zephyr",
    "Nolzur's marvelous pigments",
    "Bag of devouring",
    "Portable hole",
    ];
let magicTableE = [
    "Spell scroll(8th level)",
    "Potion of storm giant strength",
    "Potion of supreme healing",
    "Spell scroll(9th level)",
    "Universal solvent",
    "Arrow of slaying",
    "Sovereign glue"
    ];
let magicTableF = [
    "Weapon +1",
    "Shield +1",
    "Sentinel shield",
    "Amulet of proof aganist detection and location",
    "Boots of elvenkind",
    "Boots of striding and springing",
    "Bracers of archery",
    "Brooch of shielding",
    "Broom of flying",
    "Cloak of elvenkind",
    "Cloak of protection",
    "Guantlets of ogre power",
    "Hat of disguise",
    "Javelin of lighting",
    "Pearl of power",
    "Rod of the pact keeper +1",
    "Slippers of spider climbing",
    "Staff of the adder",
    "Staff of the python",
    "Sword of vengeance",
    "Trident of fish command",
    "Wand of magic missiles",
    "Wand of the war mage +1",
    "Wand of web",
    "Weapon of Warning",
    "Adamantime armor (chain mail)",
    "Adamantime armor (chain shirt)",
    "Adamantime armor (scale mail)",
    "Bag of tricks(gray)",
    "Bag of tricks(rust)",
    "Bag of tricks(tan)",
    "Boots of the winterlands",
    "Circlet of blasting",
    "Deck of illusions",
    "Eversmoking bottle",
    "Eyes of charming",
    "Eyes of the eagle",
    "Figurine of wonderous power(silver raven)",
    "Gem of brightness",
    "Gloves of missile snaring",
    "Gloves of thievery",
    "Headband of intellect",
    "Helm of telepathy",
    "Instrument of the bards (Doss lute)",
    "Instrument of the bards (Fochlucan bandore)",
    "Instrument of the bards (Mac-Fuimidh cittern)",
    "Medalion of thoughts","Periapt of wound closure",
    "Pipes of haunting",
    "Pipes of the sewers",
    "Ring of jumping",
    "Ring of mind shielding",
    "Ring of warmth",
    "Ring of water walking",
    "Quiverr of Ehlonna",
    "Stone of good luck",
    "Wind fan",
    "Winged boots"
    ];
let magicTableG = [
    "Weapon +2",
    "Figurine of wonderous power " + figurines(),
    "Adamantime armor (breastplate)",
    "Adamantime armor (splint)",
    "Amulet of health",
    "Armor of vulnerabilty",
    "Arrow-catching shield",
    "Belt of dwarvenkind",
    "Belt of hill giant strength",
    "Berserker axe",
    "Boots of levitation",
    "Boots of speed",
    "Bowl of commading water elementals",
    "Bracers of defense",
    "Brazier of commanding fire elementals",
    "Cape of the mountebank",
    "Censer of controlling air elementals",
    "Armor +1 chain mail",
    "Armor of resistance (chain mail)",
    "Armor +1 chain shirt",
    "Armor of resistance (chain shirt)",
    "Cloak of displacement",
    "Cloak of the bat",
    "Cube of force",
    "Daern's instant fortress",
    "Dagger of venom",
    "Dimensional shackles",
    "Dragon slayer",
    "Elven chain",
    "Flame tounge",
    "Gem of seeing",
    "Giant slayer",
    "Glamoured studded leather",
    "Helm of teleportation",
    "Horn of blasting",
    "Horn of Vahalla (Silver or Brass)",
    "Instrument of the bards (Canaith mandolin)",
    "Instrument of the bards (Cli lyre)",
    "Ioun stone (awarness)",
    "Ioun stone (protection)",
    "Ioun stone (reserve)",
    "Ioun stone (sustenance)",
    "Iron bands of Bilarro",
    "Armor +1 (leather)",
    "Armor of resistance (leather)",
    "Mace of disruption",
    "Mace of smiting",
    "Mace of terror",
    "Mantle of spell resistance",
    "Necklace of prayer beads",
    "Periapt of proof aganist poison",
    "Ring of animal influnce",
    "Ring of evasion",
    "Ring of feather falling",
    "Ring of free action",
    "Ring of protection",
    "Ring of resistance",
    "Ring of spell storing",
    "Ring of the ram",
    "Ring of X-ray vision",
    "Robe of Eyes",
    "Rod of rulership",
    "Rod of the pact keeper +2",
    "Rope of entanglement",
    "Armor +1 (scale mail)",
    "Armor of resistance (scale mail)",
    "Shield +2",
    "Shield of missle attraction",
    "Staff of charming",
    "Staff of healing",
    "Staff of swarming insects",
    "Staff of the woodlands",
    "Staff of withering",
    "Stone of controlling earth elementals",
    "Sun blade",
    "Sword of life stealing",
    "Sword of wounding",
    "Tentacle rod",
    "Vicious Weapon",
    "Wand of binding",
    "Wand of enemy detection",
    "Wand of fear",
    "Wand of fireballs",
    "Wand of lighting bolts",
    "Wand of paralysis",
    "Wand of the war mage +2",
    "Wand of wonder",
    "Wings of flying"
    ];
let magicTableH = [
    "Weapon +3",
    "Amulet of the planes",
    "Carpet of flying",
    "crystal ball (very rare)",
    "Ring of regeneration",
    "Ring of shooting stars",
    "Ring of telekinesis",
    "Ring of scintillating colors",
    "Robe of stars",
    "Rod of absorption",
    "Rod of alertness",
    "Rod of security","Rod of the pact keeper +3",
    "Scimitar of speed",
    "Shield +3",
    "Staff of fire",
    "Staff of frost",
    "Staff of power",
    "Staff of striking",
    "Staff of thunder and lighting",
    "Sword of sharpness",
    "Wand of polymorph",
    "Wand of the war mage +3",
    "Adamantine armor (half plate)",
    "Adamantine armor (plate)",
    "Animated Shield",
    "Belt of fire giant strength",
    "Belt of " + giants() + " giant strength",
    "Armor +1",
    "Armor of resistance (breastplate)",
    "Candle of invocation",
    "Armor +2 chain mail",
    "Armor +2 chain shirt",
    "Cloak of arachnida",
    "Dancing sword",
    "Demon armor",
    "Dragon scale mail",
    "Dwarven plate",
    "Dwarven thrower",
    "Efreeti bottle",
    "Figurine of wondrous power(obsidian steed)",
    "Frost brand",
    "Helm of brilliance",
    "Horn of Valhalla (bronze)",
    "Instrument of the bards (Anstruth harp)",
    "Ioun stone (absorption)",
    "Ioun stone (agility)",
    "Ioun stone (fortitude)",
    "Ioun stone (insight)",
    "Ioun stone (intellect)",
    "ioun stone (leadership)",
    "Ioun stone (strength)",
    "Armor +2 leather",
    "Manual of bodily health",
    "Manual of gainful exercise",
    "Manual of golems",
    "Manual of quickness of action",
    "Mirror of life trapping",
    "Nine lives stealer",
    "Oathbow",
    "Armor +2 scale mail",
    "Spellguard Shield",
    "Armor +1 splint",
    "Armor of resistance (studder leather)",
    "Tome of clear thought",
    "Tome of leadership and influence",
    "Tome of understanding"
];
let magicTableI = [
    "Defender",
    "Hammer of thunderbolts",
    "Luck blade",
    "Sword of answering",
    "Holy anvenger",
    "Ring of djinni summoning",
    "Ring of invisibility",
    "Ring of spell turning",
    "Ring of lordly might",
    "Staff of the magi",
    "Vorpal Sword",
    "Belt of cloud giant strength",
    "Armor +2 breastplate",
    "Armor +3 chain mail",
    "Armor +3 chain shirt",
    "Cloak of invisibility",
    "Crystal ball(legendary version)",
    "Armor +1 halfplate",
    "Iron flask",
    "Armor +3 leather",
    "Armor +1 plate",
    "Robe of the archmagi",
    "Rod of resurrection",
    "Armor +1 scale mail",
    "Scarab of protection",
    "Armor +2 splint",
    "Armor +2 studded leather",
    "Well of many worlds",
    //Trying to get magic armor roll a subtable to show the type
    "Magic " + magicArmorTable() ,
    "Apparatus of Kwalish",
    "Armor of invulnerability",
    "Belt of strom giant strength",
    "Cubic gate",
    "Deck of many things",
    "Efreeti chain",
    "Armor of resistance (half plate)",
    "Horn of Valhalla (iron)",
    "instrument of the bards (Ollamh harp)",
    "Ioun stone (greater absorption)",
    "Ioun stone (mastery)",
    "Ioun stone (regeneration)",
    "Plate armor of etherealness",
    "Plate armor of resistance",
    "Ring of air elemental command",
    "Ring of earth elemental command",
    "Ring of fire elemental command",
    "Ring of three wishes",
    "Ring of water elemental command",
    "Sphere of annihilation",
    "Talisman of pure good",
    "Talisman of the Sphere",
    "Talisman of ultimate evil",
    "Tome of the skilled tongue"
];

var magicTables = [
    magicTableA,
    magicTableB,
    magicTableC,
    magicTableD,
    magicTableE,
    magicTableF,
    magicTableG,
    magicTableH,
    magicTableI
];

function addArr(arr) {
    arrOfArr.push(arr);
}
function arrChooser(arr) {
    newArr = arr[Math.floor(Math.random()*arr.length)];
    return newArr;
}
function randomItem(arr) {
    return arr[Math.floor(Math.random()*arr.length)];
};
function randItemN(arr,num = 1) {
    let tempArr = [];
    let counter = 0;
    while(counter < num) {
        tempArr.push(arr[Math.floor(Math.random()*arr.length)])
        counter++;
    }
    return tempArr;
}

function magicArmorTable(){
    arr= [
        "armor +2 half plate",
        "armor +2 plate",
        "armor +3 studded leather",
        "armor +3 breastplate",
        "armor +3 splint",
        "armor +3 half plate",
        "armor +3 plate"]
            return arr[Math.floor(Math.random()*arr.length)];
    };
function figurines() {
    arr=[
        "Bronze griffon",
        "Ebony fly",
        "Golden lions",
        "Ivory goats",
        "Marble elephant",
        "Onyx dog",
        "Serpentine owl"]
        return arr[Math.floor(Math.random()*arr.length)]
};
function giants() {
    arr = [ 'frost', 'stone'];
    return arr[Math.floor(Math.random()*arr.length)];
}

let roll = randomItem(arrChooser(magicTables));

console.log('You found a ' + randomItem(arrChooser(magicTables)));
console.log(randItemN(arrChooser(magicTables), 2));

const item_results = document.getElementById("item-results")

let itemRoll = roll.join('')
const Submit_button = document.getElementById("Table-Submit");
Submit_button.addEventListener('click', function() {
    document.getElementById("item-results").innerHTML = itemRoll;
})




